version: '3'
services:
  pwa:
    restart: always
    build:
      context: ./pwa
      target: pwa-production

  server:
    restart: unless-stopped
    build:
      context: ./server
      target: server-production
    depends_on:
      - redis

  caddy:
    restart: always
    depends_on:
      - pwa
      - server
    build:
      context: ./docker/Caddy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

  redis:
    image: redis

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  caddy_data:
  caddy_config: