version: '3'
services:
  pwa:
    build:
      target: pwa-development
    volumes:
      - ./pwa:/usr/src/pwa:rw,cached

  server:
    build:
      target: server-development
    volumes:
      - ./server:/usr/src/server:rw,cached