version: '3'
services:
  pwa:
    build:
      target: pwa-development
    volumes:
      - ./pwa:/usr/src/pwa:rw,cached

  server:
    build:
      target: server-development
    volumes:
      - ./server/prisma:/usr/src/server/prisma:ro
      - ./server/src:/usr/src/server/src:ro

  db:
    ports:
      - 5432:5432
