version: '3'
services:
  client:
    build:
      target: client-development
    volumes:
      - ./client:/usr/src/client:rw,cached

  server:
    build:
      target: server-development
    volumes:
      - ./server:/usr/src/server:rw,cached
#    deploy:
#      mode: replicated
#      replicas: 3