version: '3.1'
services:
  pwa:
    restart: always
    build:
      context: ./pwa
      target: pwa-production

  server:
    restart: unless-stopped
    build:
      context: ./server
      target: server-production
    env_file: .env
    depends_on:
      - redis

  caddy:
    restart: always
    depends_on:
      - pwa
      - server
    image: caddy:2-alpine
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file: .env
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

  redis:
    image: redis:6-alpine

  db:
    image: postgres:13-alpine
    restart: always
    env_file: .env

volumes:
  caddy_data:
  caddy_config:
