export const WINDOW_TRANSITION_DURATION_IN_MILLISECONDS = 250;

export const PROCESS_DELIMITER = '__';

export const DOUBLE_CLICK_TIMEOUT_IN_MILLISECONDS = 500;

export const SHORTCUT_EXTENSION = '.uri';
